<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
<?php $this->trigger('view.show.before'); ?>

<div class="container" id="jdcMainContainer">
    <div class="row">
      <?php //echo $this->partial('JDC/nav_tools',['item'=>$item,'heading'=>$this->vars('heading')]);?>
    </div>
    <div class="row">
      <div id='jdcGraph' class='jdc' ></div>
    </div>
</div>
<?php echo $this->partial('JDC/modal_ajoutRapport');?>
<?php echo $this->partial('JDC/modal_patienter');?>
<?php echo $this->partial('JDC/modal_creerDetail');?>

<script>
    item = <?php echo json_encode($item); ?>
  window.onload = function() {
    initIhmJdc();
  };

</script>

<?php $this->trigger('view.show.after'); ?>
