<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));

$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.min.css'));

//$this->headScript()->appendFile($this->assetUrl('js/jquery-3.4.1.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/bootstrap.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/all.min.js'));//fontawesome
//$this->headScript()->appendFile($this->assetUrl('js/d3.min.js'));


$this->JsUris(['site'=>$site]);
$this->trigger('view.layout');

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
                
    </head>

    <?php echo $this->htmlElement('body'); ?>
       <!--- begin header----->
       <?php echo $this->partial('omeka/site/header'); ?>
       <!--- end header------->

        <div class="clearfix"></div>
        <div class="container">

            <?php echo $this->content; ?>
            
        </div>
        <?php echo $this->partial('JDC/footer'); ?>
    </body>
</html>
